### ISSUE TITLE
Cannot start service jacs-dashboard

### ISSUE THREAD

**Issue by freshpomelo** [JaneliaSciComp/jacs-cm#9]
Hi all,

I'm trying to install jacs-cm on Docker for Mac.
There is an error info showed below, when I tried to  bring up all of the application containers with "./manage.sh compose up standalone -d".
<img width="1374" alt="67142985-4438c500-f299-11e9-8deb-95c2ad1e8729" src="https://user-images.githubusercontent.com/10544528/67617090-1c55de00-f812-11e9-947f-85ed928b5c1e.png">

There is a solution here. https://github.com/docker/for-mac/issues/3431#issuecomment-545267759

**Comment by krokicki** [comment]
Thanks @freshpomelo for reporting this. I've updated the jacs-cm deployments to not use the shared flag, so your workaround won't be necessary in future versions. 

The shared flag is only necessary for automounted NFS volumes in Linux.

**Comment by balibebas** [comment]
@krokicki sorry for the necrobump but I'm debugging a quasi-related issue and your comment about `shared` applying to NFS/*nix had me a bit confused. Could the error received by OP be because `shared` simply isn't supported in macOS (to your knowledge) and the Docker Engine is just barfing up a spurious error message because what's being tried is, for all intents and purposes, not legal?

**Comment by ghost** [comment]
> The shared flag is only necessary for automounted NFS volumes in Linux.

To elaborate a little, they're not only _necessary_ on Linux but only _possible_ on Linux. "Bind propagation defaults to rprivate for both bind mounts and volumes. It is only configurable for bind mounts, and only on Linux host machines." ([Docker Docs](https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation)). macOS has something called _consistency_ according to [this post](https://dominikbraun.io/blog/docker/docker-bind-mounts-a-quick-summary/) but that's not a feature surfaced by the Docker Engine.
